name: Fix Submodules In CHunks

on:
  workflow_dispatch:

jobs:
  fix-submodules:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        submodule_path:
          - texts/A00
          - texts/A01
          - texts/A02
          # Add more submodule paths as necessary

    steps:
      - name: Checkout the repository without submodules
        uses: actions/checkout@v3
        with:
          submodules: false  # Avoid automatic submodule initialization

      - name: Configure HTTPS credentials
        run: |
          git config --global user.name "NatalieRMCastro"
          git config --global user.email "natalie.castro@colorado.edu"
          git config --global credential.helper store
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Use the built-in GitHub token for access

      - name: Rewrite submodule URLs to HTTPS
        run: |
          git submodule foreach --recursive '
          url=$(git config --file $toplevel/.gitmodules submodule.$name.url | sed "s/git@bitbucket.org:/https:\/\/bitbucket.org\//");
          git config --file $toplevel/.gitmodules submodule.$name.url $url;
          git submodule sync $name;
          '

      - name: Initialize and update a specific submodule
        run: |
          git submodule update --init --recursive ${{ matrix.submodule_path }}
          git submodule sync --recursive ${{ matrix.submodule_path }}
          git add ${{ matrix.submodule_path }}
          git commit -m "Fix submodule ${{ matrix.submodule_path }}" || echo "No changes to commit"
          git push origin main || echo "Nothing to push"
